language: java

sudo: required

jdk:
  - openjdk15

services:
  - docker

env:
  jobs:
     DOCKER_COMPOSE_VERSION=1.27.4
  global:
    secure: ZmhxWyKduRSuO/ZwNURW3Ct1j0nk68xkG5DbExt2cG5121ZycFY3rxJyhG97D887RWnSxjSUCypr7T3DDdglW2tZNWonvsRWbkofEotiFbOJMZH2r4GAG8oeSRhMgnpaM0tacBmBxai6BPn1rUAu2SzkKbihBB742B41hz6WhA0BjrAi1KQHpOyRQE2ZRWkU9xZNVp80gk1TFxWWiPCPxtWcFndukcznW8Y4EImHudfRgLRtxQgQjQcpp04VZiGYKoL1ogdPmBfO7KiUkGGX4Lp/JHCFsmPbVnXId994opxdh5wtYiQ0UfoYPZZzAoGeiUUVS1Kusk7qi66iDLq/tCABwC0qHMV6gI/c46QHdasmeX5fezBZQ9uBdcxsYQYTwQnN+dTVVqIv1JrtnUxDFqUcIEGEQWUM/LFrhQxtW9LLe87UvVPX45JooQVqizIuiL1SzbdtdazgXNu4/ESrKWUDG2Wcu8NcoF+VGEbvW5tiKTa09ao27VsNIZmjLN0bHEzfrCUC3gJhW0cTZMTlLLu43KjdI3ftJsUGxBoj5K9hDUNGcAELomHQlz0oenVVlxTZj70WdvCzOesIrRq9qaNbPZ7HG+2iJnDwWNTPfpg7VSXFkkS7uO806LCNTSyyB5Z1uq6oltb5aKO3td4iGgbNIfC3E15qrTxq2HAyM1Q=


before_install:
  - pip install --user awscli
  - chmod a+x gradlew
  - export PATH=$PATH:$HOME/.local/bin
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin


script:
  - docker-compose build --pull
  - docker tag tradingengine_trade-engine-prod:latest elijahahianyo/trade-project:trade-engine-prod
  - docker image ls
  - docker push elijahahianyo/trade-project:trade-engine-prod #hms-api_django-api-dev:latest
  - ls -lh
#  - aws ssm send-command --document-name "AWS-RunShellScript" --instance-ids "i-00bd5a2c279b0213d" --parameters '{"commands":["sudo docker-compose -f /home/ubuntu/docker-compose.yml up -d --no-deps --build"],"executionTimeout":["3600"]}' --timeout-seconds 600 --region eu-central-1
#deploy:
#  skip_cleanup: true
#  provider: elasticbeanstalk
#  region: "eu-central-1"
#  app: "TradeProject"
#  env: "TradeProject-env"
#  bucket_name: "elasticbeanstalk-eu-central-1-460526993529"
#  bucket_path: "TradeProject"
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
#  on:
#    branch: master

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
  skip_cleanup: true
      #  bash ./deploy.sh