version: '2'
services:
  trade-engine-prod:
    container_name: trade-engine-prod
    image: elijahahianyo/trade-project:trade-engine-prod
    ports:
      - 23000:23000
    networks:
      - trade_project

networks:
  trade_project:
    external: true